[package]
name = "comcigan-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.30"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"